version: '3.9'
services:
  web:
    build: ./web
    command: flask run --host=0.0.0.0
    ports: 
      - "5000:5000"
    volumes: 
      - ./web:/app
  # qgis-server:
  #   build: ./qgis-server
  #   ports: 
  #     - "5555:5555"
  #   volumes:
  #     - ./qgis-server/data:/data:ro
  #   environment:
  #     - LANG=en_EN.UTF-8
  #     - QGIS_SERVER_LOG_LEVEL=0
  #     - QGIS_PROJECT_FILE=/data/osm.qgs
  #     - DEBUG=1      
  # nginx:
  #   image: nginx:1.13
  #   ports:
  #   - 8080:80
  #   volumes:
  #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #   - qgis-server