version: "3.9"
services:
  web:
    build: ./web
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
      - ./geotif:/app/app/scripts/geotif/
      - ./predict_ML:/app/app/scripts/predict/

    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
